# Generated by Django 5.1.1 on 2025-07-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
